language: go

go:
  - 1.9

before_script:
  - curl https://glide.sh/get | sh

script: make build-ci

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: W13M6q1xG93BlH8HiJLfNfgbS2Ia0xj9maYrp+qD8Ltlz9vliGG+lFqbIYQQCIXEpwNeVYzayOl6kGLy+ZUAZoQUsO3WrMTDDV9IwGFQnFo3JelOw1rNR7K4RAe8sTsROyFQ49K17QxSFe69uZ+62jkUnOS3IPZBkkAYwbXgyH1FX+v+gIeoPB4PuwsteFVUr1mkZBsemTWxExyNYImht3CrjmXNzUHW3zpmJVsj14Prb/xjtGWWXCDB3WakqQyLbld74WR1Y+TIifelN+sd0pe2L2Or8ikOaU+dsRWiohUoi9ypf9cDMJXiDFnhy5DMUzV1iF5e4jrtGqTE0CNHIOUGrbnI4FYd55qvM4AohSmbUsnEXkrZD1lTdFVzoL/Chn1uVR8xyivD/4PCUzknN9dHLx1rfVlabIBMO8YL2yiUk2efJ4YhxXEQ5XCJsC0W5+ewiu+uAX7jX250JrT0GV4arpjBf7/K1L3cXQT0C+NXO6LV4R8+CBChEmylnW4m+ONx6LcV1u0XCYLyi/KR0C3XjFa/aZ1y6NuRV/xyxuBmt6FYzkhTLxHy37m8FHDrSTEYQ/215VNxMwZqUmZdrQiWT0g7YNeXMnHiDdDPsjP2hKoU4Z4TKPkbNkO3C5o0WMndBJ1fDiXvK8A98lU6OEPCgOp3wQSZsE5lH6DaTBI=
  file:
    - "./dist/kube-deploy-linux"
    - "./dist/kube-deploy-mac"
  on:
    tags: true
